#include "nsISupports.idl"

interface nsIURI;

[scriptable, uuid(ac83ae97-69a0-4217-9c1f-0e3d47973b84)]
interface nsIApplicationCacheUpdateService : nsISupports
{
	attribute unsigned long updateFrequency; 

	attribute PRTime lastUpdate; 
  /**
   * Add an application cache into update service.
   * The offline caches of these applications will be 
   * automatically updated after certain period of time.
   */
  void addEntries(in nsIURI aManifestURI, in nsIURI aDocumentURI); 

  /**
   * Remove an application cache from update service.
   */
  void removeEntries(in nsIURI aManifestURI);

  /**
   * Enable the application cache update service. Applications 
   * that have been added into this service will be automatically 
   * updated after a certain period of time.
   */
  void enableUpdate();

  /**
   * Disable the application cache update service.
   */
  void disableUpdate(); 
};
